version: '3.4'

services:
 web:
   image: nginx:stable-alpine
   restart: always
   volumes:
    - ./src:/public_html
    - ./nginx:/etc/nginx/conf.d
    - ./dhparam:/etc/nginx/dhparam
    - ./certbot/conf:/etc/nginx/ssl
    - ./certbot/data:/usr/share/nginx/html/letsencrypt
   ports:
    - 10.0.50.22:80:80
    - 10.0.50.22:443:443

 certbot:
  image: certbot/certbot:latest
  command: certonly --webroot-path=/usr/share/nginx/html/letsencrypt --email maierandrewd@gmail.com --agree-tos --no-eff-email -d local.andrewmaier.dev
  volumes:
   - ./certbot/conf:/etc/letsencrypt
   - ./certbot/logs:/var/log/letsencrypt
   - ./certbot/data:/usr/share/nginx/html/letsencrypt
